name: doctorapp
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus:
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_svg:
  google_sign_in: ^6.1.4
  country_pickers: ^2.0.0
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  pin_input_text_field: ^4.5.1
  colorful_safe_area: ^1.0.0
  intl: ^0.18.1
  pinput: ^2.2.31


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
  fonts: 
    - family: Proxima Nova
      fonts: 
        - asset: assets/fonts/ProximaNovaBold.ttf
          weight: 700
    - family: Avenir
      fonts: 
        - asset: assets/fonts/AvenirBlack.ttf
          weight: 900
        - asset: assets/fonts/AvenirHeavy.ttf
          weight: 900
        - asset: assets/fonts/AvenirRegular.ttf
          weight: 400
        - asset: assets/fonts/AvenirMedium.ttf
          weight: 500
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
    - family: SF Pro Text
      fonts: 
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProTextBold.ttf
          weight: 700
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
    - family: OCR A Extended
      fonts: 
        - asset: assets/fonts/OCRAExtended.ttf
          weight: 400
    - family: IBM Plex Sans
      fonts: 
        - asset: assets/fonts/IBMPlexSansMedium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansBold.ttf
          weight: 700
    - family: Outfit
      fonts: 
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
